/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RevanchaRouteImport } from './routes/revancha'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PlanillaRouteImport } from './routes/planilla'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevanchaIndexRouteImport } from './routes/revancha.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerificarCodigoRouteImport } from './routes/verificar.$codigo'
import { Route as RevanchaRegistroRouteImport } from './routes/revancha.registro'
import { Route as RevanchaLeaderboardRouteImport } from './routes/revancha.leaderboard'
import { Route as AdminRevanchaRouteImport } from './routes/admin.revancha'
import { Route as AdminResultadosRouteImport } from './routes/admin.resultados'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminCronogramaRouteImport } from './routes/admin.cronograma'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RevanchaRoute = RevanchaRouteImport.update({
  id: '/revancha',
  path: '/revancha',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanillaRoute = PlanillaRouteImport.update({
  id: '/planilla',
  path: '/planilla',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevanchaIndexRoute = RevanchaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevanchaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerificarCodigoRoute = VerificarCodigoRouteImport.update({
  id: '/verificar/$codigo',
  path: '/verificar/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const RevanchaRegistroRoute = RevanchaRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => RevanchaRoute,
} as any)
const RevanchaLeaderboardRoute = RevanchaLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => RevanchaRoute,
} as any)
const AdminRevanchaRoute = AdminRevanchaRouteImport.update({
  id: '/revancha',
  path: '/revancha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultadosRoute = AdminResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCronogramaRoute = AdminCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cronograma': typeof CronogramaRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/planilla': typeof PlanillaRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/revancha': typeof RevanchaRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cronograma': typeof AdminCronogramaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revancha': typeof AdminRevanchaRoute
  '/revancha/leaderboard': typeof RevanchaLeaderboardRoute
  '/revancha/registro': typeof RevanchaRegistroRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/revancha/': typeof RevanchaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/planilla': typeof PlanillaRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cronograma': typeof AdminCronogramaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revancha': typeof AdminRevanchaRoute
  '/revancha/leaderboard': typeof RevanchaLeaderboardRoute
  '/revancha/registro': typeof RevanchaRegistroRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin': typeof AdminIndexRoute
  '/revancha': typeof RevanchaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cronograma': typeof CronogramaRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/planilla': typeof PlanillaRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/revancha': typeof RevanchaRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cronograma': typeof AdminCronogramaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revancha': typeof AdminRevanchaRoute
  '/revancha/leaderboard': typeof RevanchaLeaderboardRoute
  '/revancha/registro': typeof RevanchaRegistroRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/revancha/': typeof RevanchaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cronograma'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/planilla'
    | '/registro'
    | '/reglas'
    | '/revancha'
    | '/sitemap.xml'
    | '/admin/cronograma'
    | '/admin/reportes'
    | '/admin/resultados'
    | '/admin/revancha'
    | '/revancha/leaderboard'
    | '/revancha/registro'
    | '/verificar/$codigo'
    | '/admin/'
    | '/revancha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cronograma'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/planilla'
    | '/registro'
    | '/reglas'
    | '/sitemap.xml'
    | '/admin/cronograma'
    | '/admin/reportes'
    | '/admin/resultados'
    | '/admin/revancha'
    | '/revancha/leaderboard'
    | '/revancha/registro'
    | '/verificar/$codigo'
    | '/admin'
    | '/revancha'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cronograma'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/planilla'
    | '/registro'
    | '/reglas'
    | '/revancha'
    | '/sitemap.xml'
    | '/admin/cronograma'
    | '/admin/reportes'
    | '/admin/resultados'
    | '/admin/revancha'
    | '/revancha/leaderboard'
    | '/revancha/registro'
    | '/verificar/$codigo'
    | '/admin/'
    | '/revancha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CronogramaRoute: typeof CronogramaRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PlanillaRoute: typeof PlanillaRoute
  RegistroRoute: typeof RegistroRoute
  ReglasRoute: typeof ReglasRoute
  RevanchaRoute: typeof RevanchaRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificarCodigoRoute: typeof VerificarCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revancha': {
      id: '/revancha'
      path: '/revancha'
      fullPath: '/revancha'
      preLoaderRoute: typeof RevanchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planilla': {
      id: '/planilla'
      path: '/planilla'
      fullPath: '/planilla'
      preLoaderRoute: typeof PlanillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revancha/': {
      id: '/revancha/'
      path: '/'
      fullPath: '/revancha/'
      preLoaderRoute: typeof RevanchaIndexRouteImport
      parentRoute: typeof RevanchaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verificar/$codigo': {
      id: '/verificar/$codigo'
      path: '/verificar/$codigo'
      fullPath: '/verificar/$codigo'
      preLoaderRoute: typeof VerificarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revancha/registro': {
      id: '/revancha/registro'
      path: '/registro'
      fullPath: '/revancha/registro'
      preLoaderRoute: typeof RevanchaRegistroRouteImport
      parentRoute: typeof RevanchaRoute
    }
    '/revancha/leaderboard': {
      id: '/revancha/leaderboard'
      path: '/leaderboard'
      fullPath: '/revancha/leaderboard'
      preLoaderRoute: typeof RevanchaLeaderboardRouteImport
      parentRoute: typeof RevanchaRoute
    }
    '/admin/revancha': {
      id: '/admin/revancha'
      path: '/revancha'
      fullPath: '/admin/revancha'
      preLoaderRoute: typeof AdminRevanchaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resultados': {
      id: '/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AdminResultadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cronograma': {
      id: '/admin/cronograma'
      path: '/cronograma'
      fullPath: '/admin/cronograma'
      preLoaderRoute: typeof AdminCronogramaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCronogramaRoute: typeof AdminCronogramaRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminResultadosRoute: typeof AdminResultadosRoute
  AdminRevanchaRoute: typeof AdminRevanchaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCronogramaRoute: AdminCronogramaRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminResultadosRoute: AdminResultadosRoute,
  AdminRevanchaRoute: AdminRevanchaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RevanchaRouteChildren {
  RevanchaLeaderboardRoute: typeof RevanchaLeaderboardRoute
  RevanchaRegistroRoute: typeof RevanchaRegistroRoute
  RevanchaIndexRoute: typeof RevanchaIndexRoute
}

const RevanchaRouteChildren: RevanchaRouteChildren = {
  RevanchaLeaderboardRoute: RevanchaLeaderboardRoute,
  RevanchaRegistroRoute: RevanchaRegistroRoute,
  RevanchaIndexRoute: RevanchaIndexRoute,
}

const RevanchaRouteWithChildren = RevanchaRoute._addFileChildren(
  RevanchaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CronogramaRoute: CronogramaRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PlanillaRoute: PlanillaRoute,
  RegistroRoute: RegistroRoute,
  ReglasRoute: ReglasRoute,
  RevanchaRoute: RevanchaRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificarCodigoRoute: VerificarCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
